### ISSUE TITLE
식품 추천 페이지

### ISSUE THREAD

**Issue by rptbley** [2021-SMHRD-KDT-Bigdata-3/WepPT#16]
- [x] 사용자 개개인의 용도에 맞는 식품 추천
- [x] 테이블형태로 출력
- [x] 테이블 각 컬럼은 제품사진(미정), 제품명, 칼로리, 탄수화물, 단백질, 지방 순으로 형성
- [x] 컬럼 헤드 클릭 시, 오름차순 혹은 내림차순으로 정렬이 되게 기능 설정

**Comment by Koth100** [comment]
테이블의 tbody안의 각 tr태그의 display가 flex로 설정되어있어서 테이블 형태가 어긋나는 모습을 보여줌 여기에 적용되어 있는 diplay값을 table-row로 수정해줌
