### ISSUE TITLE
다이어트 가공식품 데이터 크롤링

### ISSUE THREAD

**Issue by rptbley** [2021-SMHRD-KDT-Bigdata-3/WepPT#27]
- [x] 식품의약처데이터베이스로부터 가공식품 데이터 크롤링(식품이름, 칼로리, 탄수화물, 단백질, 지방)
- [x] 크롤링한 식품이름을 활용하여 네이버에서 제품 사진 크롤링
- [x] DB에 저장

**Comment by areum52** [comment]
error : This version of ChromeDriver only supports Chrome version 89
Current browser version is 91.0.4472.101 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by Koth100** [comment]
크롬웹드라이버의 버전이 현재 쓰고있는 브라우져 버전과 맞지 않는 문제입니다.
https://chromedriver.chromium.org/downloads
여기서 91버전 웹드라이버를 받으시기 바랍니다.

**Comment by areum52** [comment]
유튜브 크롤링 중에 검색키워드 입력할때 오류가 뜹니다
Message: element not interactable
  (Session info: chrome=91.0.4472.101)
