### ISSUE TITLE
동영상

### ISSUE THREAD

**Issue by skdusgh** [2021-SMHRD-KDT-Bigdata-3/WepPT#34]
클릭에 따라서 각각 부위별로 다른 동영상 보이는 방법

**Comment by Koth100** [comment]
클릭이 걸려있는 form태그의 action값을 현재 페이지로 하고, 현재 페이지를 구성할 때 해당 부위값이 비어있다면(초기화면) 복근운동을 불러오게, 부위값이 있다면 해당 부위값에 맞는 영상들만 DAO를 통해 불러오도록 지도
