### ISSUE TITLE
캘린터 클릭문제

### ISSUE THREAD

**Issue by Koth100** [2021-SMHRD-KDT-Bigdata-3/WepPT#36]
클릭 시 다른 부분이 클릭됨
오늘날짜가 아닌 다른 날짜로 등록 시 정상 작동함

**Comment by Koth100** [comment]
js파일 다른 내용 사용하여 해결 완료
확인 후 본인팀의 성향에 따라 수정할 것

**Comment by JooSeunghyeon** [comment]
감사합니다

2021년 6월 22일 (화) 오후 12:17, 이상준 ***@***.***>님이 작성:
